/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlControlador;
import Controlador.CtrlControladorIE;
import Controlador.GUINC;
import Modelo.ConsultasEstudiantes;
import Modelo.ConsultasRegistroUsuarios;
import Modelo.RegistroAsignaturas;
import Modelo.RegistroFacultad;
import Modelo.RegistroUsuarios;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dinan
 */
public class frmLoguinNC extends GUINC {

    /**
     * Creates new form frmLoguinNC
     */
    
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    //metodo en donde se implementa polimoorfismo estático puesto que ya está definido 
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Loguin";
    }  
    
    //contructor
    public frmLoguinNC() {
        //inicia los componentes jframes
        initComponents();
        //centrar el Jframe en pantalla
        this.setLocationRelativeTo(null);
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);  
        
        String [] usuario1 = new String[500];
        usuario1[0] = "SuperAdmin";
        usuario1[1] = "Administrador";
        usuario1[2] = "Docente";
        usuario1[3] = "Estudiante";
        for (int i = 0; i < 4 ; i++){
            this.Usuario.addItem(usuario1[i]);
        }
        
        //crear objeto imagen que se almacene el jlaber lblfondo        
        ImageIcon imagen = new ImageIcon ("src/imagenes/logo_blanco.jpg");
        ImageIcon imagen2 = new ImageIcon ("src/imagenes/logo_azul.jpg");
        Icon logo1 = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));  
        Icon logo2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblfondo1.getWidth(), lblfondo1.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(logo1);
        lblfondo1.setIcon(logo2);
        //this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblfondo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        Usuario = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, -1));

        jLabel1.setText("Iniciar Sesion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 143, -1, -1));

        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 178, -1, -1));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 209, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 175, 140, -1));

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 206, 140, -1));

        Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo_Usuario" }));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 244, 200, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 292, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        lblfondo.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        ConsultasRegistroUsuarios modeloLSQL = new ConsultasRegistroUsuarios();
        RegistroUsuarios modelo = new RegistroUsuarios();
        //convertir el campo contraseña de la vista en string 
        String contraseniafield = new String(txtContrasenia.getPassword());
        String TipoUsuarioValidacion;
        //string con comentario de error
        String ErrorLoguin;
        ErrorLoguin = "Su usuario, tipo de usuario, o contraseña es incorrecto";
        if(!txtUsuario.getText().equals("") && (!contraseniafield.equals(""))){
        
            modelo.setUsuario(txtUsuario.getText());
            modelo.setContrasenia(contraseniafield);
            
            
            switch(Usuario.getSelectedIndex()){
                
            
                case 0:
                    JOptionPane.showMessageDialog(null,"Seleccione un tipo de Usuario");
                    break;
                
                case 1:
                    //añadir swich case
                    // nota verificar como encriptar a md5 String nuevopass = hash.sha1(pass);
                    TipoUsuarioValidacion = "SuperAdmin";   
                    
                    modelo.setTipoUsuario(TipoUsuarioValidacion);
                    if(modeloLSQL.Loguin(modelo)){
                         JOptionPane.showMessageDialog(null,"Bienvenido SuperAdministrador");
                                /*envíar al siguiente frame*/
                                frmVentanaAdmin pantallaVA = new frmVentanaAdmin();
                                //si es correcto la pantalla será visible
                                pantallaVA.setVisible(true);
                                //cambiar de frame loguin a inicio_superadmin
                                this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, ErrorLoguin);
                    }
                    break;
                case 2:
                    TipoUsuarioValidacion = "Admin";   
                    
                    modelo.setTipoUsuario(TipoUsuarioValidacion);
                    if(modeloLSQL.Loguin(modelo)){
                        
                        JOptionPane.showMessageDialog(null,"Bienvenido Administrador");
                         
                        /*envíar al siguiente frame*/
                        frmVentanaAdmin pantallaVA = new frmVentanaAdmin();
                        //si es correcto la pantalla será visible
                        pantallaVA.setVisible(true);
                        //cambiar de frame loguin a inicio_superadmin
                        this.dispose(); 
                         
                         
                        //no borrar por seguridad 
                        /*si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
                        creamos los objetos
                        RegistroUsuarios mod = new RegistroUsuarios();
                        ConsultasRegistroUsuarios modC = new ConsultasRegistroUsuarios();
                        frmRegistroUsuarios frm = new frmRegistroUsuarios();

                        llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
                        CtrlControlador ctrl = new CtrlControlador(mod, modC, frm);
                        ctrl.iniciar();
                        frm.setVisible(true);*/
                    }
                    else{
                        JOptionPane.showMessageDialog(null, ErrorLoguin);
                    }
                    break;
                
                case 3:
                    
                    TipoUsuarioValidacion = "Docente";   
                    
                    modelo.setTipoUsuario(TipoUsuarioValidacion);
                    if(modeloLSQL.Loguin(modelo)){
                        JOptionPane.showMessageDialog(null,"Bienvenido Docente");
                         
                        /*envíar al siguiente frame*/
                        frmVentanaDocente pantallaVD = new frmVentanaDocente();
                        //si es correcto la pantalla será visible
                        pantallaVD.setVisible(true);
                        //cambiar de frame loguin a inicio_superadmin
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, ErrorLoguin);
                    }
                    break;
                
                case 4:
                    
                    TipoUsuarioValidacion = "Estudiante";
                    
                    modelo.setTipoUsuario(TipoUsuarioValidacion);
                    if(modeloLSQL.Loguin(modelo)){
                        JOptionPane.showMessageDialog(null,"Bienvenido Estudiante");
                        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
                        //creamos los objetos
                        RegistroAsignaturas modRA = new RegistroAsignaturas();
                        RegistroFacultad modRF = new RegistroFacultad();
                        ConsultasEstudiantes modCCE = new ConsultasEstudiantes();
                        inicio_estudianteNC frmIE = new inicio_estudianteNC();

                        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
                        CtrlControladorIE ctrl = new CtrlControladorIE(modRA, modRF, modCCE, frmIE);
                        ctrl.iniciar();
                        frmIE.setVisible(true);
                        frmIE.tipouser = "Estudiante";
                        this.dispose();
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, ErrorLoguin);
                    }
                    break;
            }
        }
        else{
            /*imprime sin la pantalla*/
            System.out.println("Campo vacío");
            /*imprime en pantalla externa*/
            JOptionPane.showMessageDialog(null,"Algún campo está vacío");
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //crea un boton de salir 
        this.Salir(evt);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoguinNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoguinNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoguinNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoguinNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoguinNC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Usuario;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondo1;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
