/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GUINC;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author dinan
 */
public class frmRegistroFacultad extends GUINC {
    String tipouser;
    /**
     * Creates new form frmRegistroFacultad
     */
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    //metodo en donde se implementa polimoorfismo estático puesto que ya está definido 
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Administrador de Facultades";
    }   
    
    public frmRegistroFacultad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreRF = new javax.swing.JTextField();
        txtZonaRF = new javax.swing.JTextField();
        btnBuscarRF = new javax.swing.JButton();
        txtIdRF = new javax.swing.JTextField();
        btnGuardarRF = new javax.swing.JButton();
        btnModificarRF = new javax.swing.JButton();
        btnEliminarRF = new javax.swing.JButton();
        BtnLimpiarRF = new javax.swing.JButton();
        BtnSalirRF = new javax.swing.JButton();
        btnVolverRF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel2.setText("Zona");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 37, -1));
        getContentPane().add(txtNombreRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 77, 118, -1));
        getContentPane().add(txtZonaRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 117, 118, -1));

        btnBuscarRF.setText("Buscar");
        getContentPane().add(btnBuscarRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 76, 80, -1));
        getContentPane().add(txtIdRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 117, 80, -1));

        btnGuardarRF.setText("Guardar");
        getContentPane().add(btnGuardarRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 172, 80, -1));

        btnModificarRF.setText("Modificar");
        getContentPane().add(btnModificarRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, -1));

        btnEliminarRF.setText("Eliminar");
        getContentPane().add(btnEliminarRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 172, 80, -1));

        BtnLimpiarRF.setText("Limpiar");
        getContentPane().add(BtnLimpiarRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        BtnSalirRF.setText("Salir");
        BtnSalirRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRFActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalirRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, -1));

        btnVolverRF.setText("Volver");
        btnVolverRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRFActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRFActionPerformed
        // botón de salir
        this.Salir(evt);
    }//GEN-LAST:event_BtnSalirRFActionPerformed

    private void btnVolverRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRFActionPerformed
        switch(tipouser){
            
            case "admin":
                /*envíar al siguiente frame*/
                frmVentanaAdmin pantallaAdmin = new frmVentanaAdmin();
                //si es correcto la pantalla será visible
                pantallaAdmin.setVisible(true);
                //cambiar de frame loguin a inicio_superadmin
                this.dispose();
                break;
                
            case "docente":
                /*envíar al siguiente frame*/
                frmVentanaDocente pantallaDocente = new frmVentanaDocente();
                //si es correcto la pantalla será visible
                pantallaDocente.setVisible(true);
                //cambiar de frame loguin a inicio_superadmin
                this.dispose();
                
                break;
        }
    }//GEN-LAST:event_btnVolverRFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroFacultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroFacultad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnLimpiarRF;
    public javax.swing.JButton BtnSalirRF;
    public javax.swing.JButton btnBuscarRF;
    public javax.swing.JButton btnEliminarRF;
    public javax.swing.JButton btnGuardarRF;
    public javax.swing.JButton btnModificarRF;
    public javax.swing.JButton btnVolverRF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtIdRF;
    public javax.swing.JTextField txtNombreRF;
    public javax.swing.JTextField txtZonaRF;
    // End of variables declaration//GEN-END:variables
}
