/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GUINC;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author dinan
 */
public class frmRegistroAsignaturas extends GUINC {
    
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    //metodo en donde se implementa polimoorfismo estático puesto que ya está definido 
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Administrador de Asignaturas";
    }  

    /**
     * Creates new form frmRegistroAsignaturas
     */
    public frmRegistroAsignaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentariosRA = new javax.swing.JTextPane();
        txtAcronimoRA = new javax.swing.JTextField();
        txtNombreRA = new javax.swing.JTextField();
        txtGrupoRA = new javax.swing.JTextField();
        txtHorarioRA = new javax.swing.JTextField();
        btnBuscarRA = new javax.swing.JButton();
        btnLimpiarRA = new javax.swing.JButton();
        btnEliminarRA = new javax.swing.JButton();
        btnVolverRA = new javax.swing.JButton();
        btnGuardarRA = new javax.swing.JButton();
        btnSalirRA = new javax.swing.JButton();
        btnModificarRA = new javax.swing.JButton();
        txtIdRA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Acrónimo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 52, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 92, -1, -1));

        jLabel3.setText("Grupo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 132, -1, -1));

        jLabel4.setText("Horario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 170, -1, -1));

        jLabel5.setText("Comentarios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 205, -1, -1));

        jScrollPane2.setViewportView(txtComentariosRA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 50));

        txtAcronimoRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcronimoRAActionPerformed(evt);
            }
        });
        getContentPane().add(txtAcronimoRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 49, 170, -1));
        getContentPane().add(txtNombreRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 89, 170, -1));
        getContentPane().add(txtGrupoRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 129, 170, -1));
        getContentPane().add(txtHorarioRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 167, 170, -1));

        btnBuscarRA.setText("Buscar");
        getContentPane().add(btnBuscarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 80, -1));

        btnLimpiarRA.setText("Limpiar");
        btnLimpiarRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarRAActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, -1));

        btnEliminarRA.setText("Eliminar");
        getContentPane().add(btnEliminarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 80, -1));

        btnVolverRA.setText("Volver");
        getContentPane().add(btnVolverRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 80, -1));

        btnGuardarRA.setText("Guardar");
        getContentPane().add(btnGuardarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, -1));

        btnSalirRA.setText("Salir");
        btnSalirRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRAActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, -1));

        btnModificarRA.setText("Modificar");
        getContentPane().add(btnModificarRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 80, -1));
        getContentPane().add(txtIdRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcronimoRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcronimoRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcronimoRAActionPerformed

    private void btnLimpiarRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarRAActionPerformed

    private void btnSalirRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRAActionPerformed
        //botón salir
        this.Salir(evt);
    }//GEN-LAST:event_btnSalirRAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroAsignaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarRA;
    public javax.swing.JButton btnEliminarRA;
    public javax.swing.JButton btnGuardarRA;
    public javax.swing.JButton btnLimpiarRA;
    public javax.swing.JButton btnModificarRA;
    public javax.swing.JButton btnSalirRA;
    public javax.swing.JButton btnVolverRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField txtAcronimoRA;
    public javax.swing.JTextPane txtComentariosRA;
    public javax.swing.JTextField txtGrupoRA;
    public javax.swing.JTextField txtHorarioRA;
    public javax.swing.JTextField txtIdRA;
    public javax.swing.JTextField txtNombreRA;
    // End of variables declaration//GEN-END:variables
}
