/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlControlador;
import Modelo.ConsultasRegistroUsuarios;
import Modelo.RegistroUsuarios;
//import Vista.frmRegistroUsuarios;
import Controlador.CtrlControladorRF;
import Modelo.ConsultasRegistroFacultad;
//import Modelo.RegistroFacultad;
//import Vista.frmRegistroFacultad;
import Controlador.CtrlControladorRA;
import Modelo.ConsultasRegistroAsignaturas;
//import Modelo.RegistroAsignaturas;
//import Vista.frmRegistroAsignaturas;
import Controlador.CtrlControladorIE;
import Modelo.ConsultasEstudiantes;
import Modelo.RegistroAsignaturas;
import Modelo.RegistroFacultad;
//import Vista.inicio_estudianteNC;
/**
 *
 * @author dinan
 */
public class frmVentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmVentanaDocente
     */
    public frmVentanaAdmin() {
        //inicia los componentes jframes
        initComponents();
        //centrar el Jframe en pantalla
        this.setLocationRelativeTo(null);
        //Bloquea el tamaño de la ventana//
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRUAdmin = new javax.swing.JButton();
        btnRAadmin = new javax.swing.JButton();
        btnRFAdmin = new javax.swing.JButton();
        btnCEAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRUAdmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnRUAdmin.setText("Registro Usuarios");
        btnRUAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUAdminActionPerformed(evt);
            }
        });

        btnRAadmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnRAadmin.setText("REgistro asignaturas");
        btnRAadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAadminActionPerformed(evt);
            }
        });

        btnRFAdmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnRFAdmin.setText("Registro facultades");
        btnRFAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRFAdminActionPerformed(evt);
            }
        });

        btnCEAdmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnCEAdmin.setText("Consulta estudiantes");
        btnCEAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCEAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRUAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnRUAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRAadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCEAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRUAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUAdminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroUsuarios mod = new RegistroUsuarios();
        ConsultasRegistroUsuarios modC = new ConsultasRegistroUsuarios();
        frmRegistroUsuarios frm = new frmRegistroUsuarios();
        
        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControlador ctrl = new CtrlControlador(mod, modC, frm);
        ctrl.iniciar();
        frm.setVisible(true);
        frm.tipouser = "admin";
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnRUAdminActionPerformed

    private void btnRFAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRFAdminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroFacultad modRF = new RegistroFacultad();
        ConsultasRegistroFacultad modCRF = new ConsultasRegistroFacultad();
        frmRegistroFacultad frmRF = new frmRegistroFacultad();
        
        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControladorRF ctrl = new CtrlControladorRF(modRF, modCRF, frmRF);
        ctrl.iniciar();
        frmRF.setVisible(true);
        frmRF.tipouser = "admin"; 
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnRFAdminActionPerformed

    private void btnRAadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAadminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroAsignaturas modRA = new RegistroAsignaturas();
        ConsultasRegistroAsignaturas modCRA = new ConsultasRegistroAsignaturas();
        frmRegistroAsignaturas frmRA = new frmRegistroAsignaturas();
        
        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControladorRA ctrl = new CtrlControladorRA(modRA, modCRA, frmRA);
        ctrl.iniciar();
        frmRA.setVisible(true);
        frmRA.tipouser = "admin";          
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnRAadminActionPerformed

    private void btnCEAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEAdminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroAsignaturas modRA = new RegistroAsignaturas();
        RegistroFacultad modRF = new RegistroFacultad();
        ConsultasEstudiantes modCCE = new ConsultasEstudiantes();
        inicio_estudianteNC frmIE = new inicio_estudianteNC();
        
        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControladorIE ctrl = new CtrlControladorIE(modRA, modRF, modCCE, frmIE);
        ctrl.iniciar();
        frmIE.setVisible(true);
        frmIE.tipouser = "admin";
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnCEAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCEAdmin;
    private javax.swing.JButton btnRAadmin;
    private javax.swing.JButton btnRFAdmin;
    private javax.swing.JButton btnRUAdmin;
    // End of variables declaration//GEN-END:variables
}
