/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlControladorIE;
import Controlador.CtrlControladorRA;
import Modelo.ConsultasEstudiantes;
import Modelo.ConsultasRegistroAsignaturas;
import Modelo.RegistroAsignaturas;
import Modelo.RegistroFacultad;

/**
 *
 * @author dinan
 */
public class frmVentanaDocente extends javax.swing.JFrame {

    /**
     * Creates new form frmVentanaDocente
     */
    public frmVentanaDocente() {
        //inicia los componentes jframes
        initComponents();
        //centrar el Jframe en pantalla
        this.setLocationRelativeTo(null);
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRAadmin = new javax.swing.JButton();
        btnCEAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRAadmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnRAadmin.setText("REgistro asignaturas");
        btnRAadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAadminActionPerformed(evt);
            }
        });

        btnCEAdmin.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        btnCEAdmin.setText("Consulta estudiantes");
        btnCEAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCEAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnRAadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCEAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRAadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAadminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroAsignaturas modRA = new RegistroAsignaturas();
        ConsultasRegistroAsignaturas modCRA = new ConsultasRegistroAsignaturas();
        frmRegistroAsignaturas frmRA = new frmRegistroAsignaturas();

        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControladorRA ctrl = new CtrlControladorRA(modRA, modCRA, frmRA);
        ctrl.iniciar();
        frmRA.setVisible(true);
        frmRA.tipouser = "docente";
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnRAadminActionPerformed

    private void btnCEAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEAdminActionPerformed
        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
        //creamos los objetos
        RegistroAsignaturas modRA = new RegistroAsignaturas();
        RegistroFacultad modRF = new RegistroFacultad();
        ConsultasEstudiantes modCCE = new ConsultasEstudiantes();
        inicio_estudianteNC frmIE = new inicio_estudianteNC();

        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
        CtrlControladorIE ctrl = new CtrlControladorIE(modRA, modRF, modCCE, frmIE);
        ctrl.iniciar();
        frmIE.setVisible(true);
        //cambiar de frame loguin a inicio_superadmin
        this.dispose();
    }//GEN-LAST:event_btnCEAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCEAdmin;
    private javax.swing.JButton btnRAadmin;
    // End of variables declaration//GEN-END:variables
}
