/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Controlador.GUINC;

/**
 *
 * @author dinan
 */
public class inicio_estudianteNC extends GUINC {

    String tipouser;
    
    /**
     * Creates new form inicio_estudianteNC
     */
    
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    //metodo en donde se implementa polimoorfismo estático puesto que ya está definido 
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Usuario";
    }
    public inicio_estudianteNC() {
        
        //inicia los componentes graficos del formulario
        initComponents();
        
        //centrar el jFrame        
        this.setLocationRelativeTo(null);
        
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);
        
        //arreglo de la lista - borrador no es el completo
        String [] facultad = new String[500];
        facultad[0] = "Biología";
        facultad[1] = "Medicina";
        facultad[2] = "Química";
        facultad[3] = "Filosofía";
        
        for (int i = 0; i < 4 ; i++){
            this.Facultades_NC.addItem(facultad[i]);
        }
        
        String [] Asignatura = new String[500];
        Asignatura[0] = "Matemáticas Básica";
        Asignatura[1] = "Ingeniería Económica";
        Asignatura[2] = "Ingeniería de Software I";
        Asignatura[3] = "Ingeniería de Software II";
        
        for (int i = 0; i < 4; i++){
            this.Asignatura_NC.addItem(Asignatura[i]);
        }
        //instancia imagenIncicioMI referente al label Mostrar_imagen
        ImageIcon imagenInicioMI = new ImageIcon ("src/imagenes/ImagenCiudaduniversitaria.jpg");
        ImageIcon imagePortada = new ImageIcon ("src/imagenes/logo_blanco.jpg");
        Icon logoMI = new ImageIcon(imagenInicioMI.getImage().getScaledInstance(Mostrar_imagen.getWidth(), Mostrar_imagen.getHeight(), Image.SCALE_DEFAULT));
        Icon logoP = new ImageIcon(imagePortada.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT)); 
        Mostrar_imagen.setIcon(logoMI);
        lblfondo.setIcon(logoP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Mostrar_imagen = new javax.swing.JLabel();
        Mostrar_asignatura = new javax.swing.JLabel();
        Facultades_NC = new javax.swing.JComboBox<>();
        Asignatura_NC = new javax.swing.JComboBox<>();
        Buscar_imagen = new javax.swing.JButton();
        btnSalirIE = new javax.swing.JButton();
        txtFacultadIE = new javax.swing.JTextField();
        txtAsignaturaIE = new javax.swing.JTextField();
        txtIdRF = new javax.swing.JTextField();
        txtIdRA = new javax.swing.JTextField();
        txtGrupoRA = new javax.swing.JTextField();
        btnVolverIE = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mostrar_imagen.setText("jLabel1");
        jPanel2.add(Mostrar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 200));

        Mostrar_asignatura.setText("Asignatura");
        jPanel2.add(Mostrar_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 390, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, 390, 230));

        Facultades_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultad" }));
        Facultades_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facultades_NCActionPerformed(evt);
            }
        });
        jPanel1.add(Facultades_NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 170, -1));

        Asignatura_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignatura" }));
        Asignatura_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asignatura_NCActionPerformed(evt);
            }
        });
        jPanel1.add(Asignatura_NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 170, -1));

        Buscar_imagen.setText("Buscar");
        Buscar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_imagenActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 94, -1));

        btnSalirIE.setText("Salir");
        btnSalirIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirIEActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 360, 94, -1));
        jPanel1.add(txtFacultadIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, -1));
        jPanel1.add(txtAsignaturaIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, -1));
        jPanel1.add(txtIdRF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, -1));
        jPanel1.add(txtIdRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, -1));
        jPanel1.add(txtGrupoRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 110, -1));

        btnVolverIE.setText("Volver");
        btnVolverIE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverIEActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 94, -1));
        jPanel1.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Asignatura_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asignatura_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Asignatura_NCActionPerformed

    private void Facultades_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facultades_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facultades_NCActionPerformed

    private void btnSalirIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirIEActionPerformed
        //crea un botón de salir.
        /*JOptionPane.showMessageDialog(null,"Hasta luego"); 
        System.exit(WIDTH);*/
        this.Salir(evt); 
    }//GEN-LAST:event_btnSalirIEActionPerformed

    private void Buscar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_imagenActionPerformed
        /*//switch case que llamará la imagen
        String mensaje_imagen1 = null;
        String mensaje_asignatura = null;
        int id_asignatura = 0;
        switch(Facultades_NC.getSelectedIndex()){
            case 0:
                
                //mensaje imagen se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_imagen1 = "Universidad Nacional Sede Bogotá";
                //crear objeto imagen que se establecerá en un label
                ImageIcon imagen = new ImageIcon ("src/imagenes/logo_azul.jpg");
                Icon logo1 = new ImageIcon(imagen.getImage().getScaledInstance(Mostrar_imagen.getWidth(), Mostrar_imagen.getHeight(), Image.SCALE_DEFAULT));
                Mostrar_imagen.setIcon(logo1);
                Mostrar_imagen.setVisible(true);
                this.repaint();                
                break;
            case 1:
                mensaje_imagen1 = "Imagen zona 1 de la universidad";                
                //crear objeto imagen que se establecerá en un label
                ImageIcon imagen11 = new ImageIcon ("src/imagenes/logo_blanco.jpg");
                Icon logo11 = new ImageIcon(imagen11.getImage().getScaledInstance(Mostrar_imagen.getWidth(), Mostrar_imagen.getHeight(), Image.SCALE_DEFAULT));
                Mostrar_imagen.setIcon(logo11);
                this.repaint();
                break;

            case 2:
                mensaje_imagen1 = "Imagen zona 2 de la universidad";
                break;
            case 3:
                mensaje_imagen1 = "Imagen zona 3 de la universidad";
                break; 
            case 4:
                mensaje_imagen1 = "Imagen zona 4 de la universidad";
                break;
        
        }
        switch(Asignatura_NC.getSelectedIndex()){
            case 0:
                //mensaje Asignatura se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_asignatura = "Universidad Nacional Sede Bogotá";
                break;
            case 1:
                mensaje_asignatura = "Matemáticas Básica";
                id_asignatura = 1;
                break;
            case 2:
                mensaje_asignatura = "Ingeniería Económica";
                id_asignatura = 2;
                break;
            case 3:
                mensaje_asignatura = "Ingeniería de Software I";
                id_asignatura = 3;
                break; 
            case 4:
                mensaje_asignatura = "Ingeniería de Software II";
                id_asignatura = 4;
                break;
        
        }
        Mostrar_imagen.setText("" + mensaje_imagen1);
        //centrar label
        Mostrar_imagen.setHorizontalAlignment(0);        
        Mostrar_asignatura.setText("" + mensaje_asignatura + id_asignatura);
        
      */
    }//GEN-LAST:event_Buscar_imagenActionPerformed

    private void btnVolverIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverIEActionPerformed
        switch(tipouser){
            
            case "admin":
                /*envíar al siguiente frame*/
                frmVentanaAdmin pantallaAdmin = new frmVentanaAdmin();
                //si es correcto la pantalla será visible
                pantallaAdmin.setVisible(true);
                //cambiar de frame loguin a inicio_superadmin
                this.dispose();
                break;
                
            case "docente":
                /*envíar al siguiente frame*/
                frmVentanaDocente pantallaDocente = new frmVentanaDocente();
                //si es correcto la pantalla será visible
                pantallaDocente.setVisible(true);
                //cambiar de frame loguin a inicio_superadmin
                this.dispose();
                
                break;
                
            case "Estudiante":
                JOptionPane.showMessageDialog(null,"Upss... No puedes regresar más");
                break;
                
        }
    }//GEN-LAST:event_btnVolverIEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_estudianteNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_estudianteNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_estudianteNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_estudianteNC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_estudianteNC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Asignatura_NC;
    public javax.swing.JButton Buscar_imagen;
    public javax.swing.JComboBox<String> Facultades_NC;
    public javax.swing.JLabel Mostrar_asignatura;
    public javax.swing.JLabel Mostrar_imagen;
    public javax.swing.JButton btnSalirIE;
    public javax.swing.JButton btnVolverIE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblfondo;
    public javax.swing.JTextField txtAsignaturaIE;
    public javax.swing.JTextField txtFacultadIE;
    public javax.swing.JTextField txtGrupoRA;
    public javax.swing.JTextField txtIdRA;
    public javax.swing.JTextField txtIdRF;
    // End of variables declaration//GEN-END:variables
}
