/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Controlador.GUINC;
import Iniciadores.CrudRegistroUsuarios;
import Controlador.CtrlControlador;
import Modelo.ConsultasRegistroUsuarios;
import Modelo.RegistroUsuarios;
import Vista.frmRegistroUsuarios;
/**
 *
 * @author dinan
 */
public class LoguinNC1 extends GUINC {

    /**
     * Creates new form LoguinNC1
     */
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    //metodo en donde se implementa polimoorfismo estático puesto que ya está definido 
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Loguin";
    }       
    //constructor 
    public LoguinNC1() {
        //inicia los componentes jframes
        initComponents();
        //centrar el Jframe en pantalla
        this.setLocationRelativeTo(null);
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);  
        
        String [] usuario1 = new String[20];
        usuario1[0] = "SuperAdmin";
        usuario1[1] = "Administrador";
        usuario1[2] = "Docente";
        usuario1[3] = "Estudiante";
        for (int i = 0; i < 4 ; i++){
            this.Usuario.addItem(usuario1[i]);
        }
        
        //crear objeto imagen que se almacene el jlaber lblfondo
        ImageIcon imagen = new ImageIcon ("src/imagenes/logo_azul.jpg");
        ImageIcon imagen2 = new ImageIcon ("src/imagenes/logo_blanco.jpg");
        Icon logo1 = new ImageIcon(imagen.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));  
        Icon logo2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblfondo1.getWidth(), lblfondo1.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(logo1);
        lblfondo1.setIcon(logo2);
        //this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblfondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Usuario = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblfondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 29, 205, 110));

        jLabel1.setText("Iniciar Sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 126, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 126, -1));

        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo_Usuario" }));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 205, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 270, 80, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));
        jPanel1.add(lblfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //crea un botón de salir.
        /*JOptionPane.showMessageDialog(null,"Hasta luego"); 
        System.exit(WIDTH);*/
        this.Salir(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Botón de ingresar*/    
        String usuario = jTextField1.getText();
        String contraseña = jPasswordField1.getText();
        String ErrorLoguin;
        ErrorLoguin = "Su usuario, tipo de usuario, o contraseña es incorrecto";
        /*valida si los campos están vacíos*/
        if(usuario.isEmpty() || contraseña.isEmpty()){
            /*imprime sin la pantalla*/
            System.out.println("Campo vacío");
            /*imprime en pantalla externa*/
            JOptionPane.showMessageDialog(null,"Algún campo está vacío");
        }
        else{
            switch(Usuario.getSelectedIndex()){
                case 0:
                    JOptionPane.showMessageDialog(null,"Seleccione un tipo de Usuario");
                    break;
                case 1:
                    //valida el usuario1 y contraseña que es 1234 versión anterior
                    if(usuario.equals("SuperAdmin") && contraseña.equals("Admin")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudianteNC pantallaIE = new inicio_estudianteNC();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_superadmin
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 2:
                    if(usuario.equals("Admin") && contraseña.equals("Admin")){
                        //JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        //CrudRegistroUsuarios pantallaCRU = new CrudRegistroUsuarios();
                        //si es correcto la pantalla será visible
                        //pantallaCRU.setVisible(true);
                        //cambiar de frame loguin a inicio_admin
                        //this.dispose();
                        
                        //si lo queremos llamar en el loguin ingresamos estos parámetros en el swich case
                        //creamos los objetos
                        RegistroUsuarios mod = new RegistroUsuarios();
                        ConsultasRegistroUsuarios modC = new ConsultasRegistroUsuarios();
                        frmRegistroUsuarios frm = new frmRegistroUsuarios();

                        // llamamos el constructor que me va a recibir el modelo mod, las consultas modC y la vista frm
                        CtrlControlador ctrl = new CtrlControlador(mod, modC, frm);
                        ctrl.iniciar();
                        frm.setVisible(true);

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 3:
                    if(usuario.equals("Docente") && contraseña.equals("1234")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudianteNC pantallaIE = new inicio_estudianteNC();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_Docente
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 4:
                    if(usuario.equals("Estudiante") && contraseña.equals("12345")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudianteNC pantallaIE = new inicio_estudianteNC();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_estudianteNC
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
            }
        
       
       
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoguinNC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoguinNC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoguinNC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoguinNC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoguinNC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblfondo1;
    // End of variables declaration//GEN-END:variables
}
