/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package narrowcompassGUI;

import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dinan
 */
public class inicio_estudiante extends GUINC {

    /**
     * Creates new form inicio_estudiante
     */
    
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,"Hasta luego"); 
        System.exit(WIDTH);     
    }
    
    public inicio_estudiante() {
        
        //inicia los componentes graficos del formulario
        initComponents();
        
        //centrar el jFrame        
        this.setLocationRelativeTo(null);
        
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);
        
        //arreglo de la lista - borrador no es el completo
        String [] facultad = new String[500];
        facultad[0] = "Biología";
        facultad[1] = "Medicina";
        facultad[2] = "Química";
        facultad[3] = "Filosofía";
        
        for (int i = 0; i < 4 ; i++){
            this.Facultades_NC.addItem(facultad[i]);
        }
        
        String [] Asignatura = new String[500];
        Asignatura[0] = "Matemáticas Básica";
        Asignatura[1] = "Ingeniería Económica";
        Asignatura[2] = "Ingeniería de Software I";
        Asignatura[3] = "Ingeniería de Software II";
        
        for (int i = 0; i < 4; i++){
            this.Asignatura_NC.addItem(Asignatura[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Mostrar_imagen = new javax.swing.JLabel();
        Mostrar_asignatura = new javax.swing.JLabel();
        Facultades_NC = new javax.swing.JComboBox<>();
        Asignatura_NC = new javax.swing.JComboBox<>();
        Buscar_imagen = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mostrar_imagen.setText("jLabel1");
        jPanel2.add(Mostrar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 118));

        Mostrar_asignatura.setText("Asignatura");
        jPanel2.add(Mostrar_asignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 226, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 220, 160));

        Facultades_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultad" }));
        Facultades_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facultades_NCActionPerformed(evt);
            }
        });
        jPanel1.add(Facultades_NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 94, -1));

        Asignatura_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignatura" }));
        Asignatura_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asignatura_NCActionPerformed(evt);
            }
        });
        jPanel1.add(Asignatura_NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 94, -1));

        Buscar_imagen.setText("Buscar");
        Buscar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_imagenActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 94, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 94, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Asignatura_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asignatura_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Asignatura_NCActionPerformed

    private void Facultades_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facultades_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Facultades_NCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //crea un botón de salir.
        /*JOptionPane.showMessageDialog(null,"Hasta luego"); 
        System.exit(WIDTH);*/
        this.Salir(evt); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Buscar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_imagenActionPerformed
        //switch case que llamará la imagen
        String mensaje_imagen1 = null;
        String mensaje_asignatura = null;
        int id_asignatura = 0;
        switch(Facultades_NC.getSelectedIndex()){
            case 0:
                
                //mensaje imagen se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_imagen1 = "Universidad Nacional Sede Bogotá";
                //crear objeto imagen que se establecerá en un label
                ImageIcon imagen = new ImageIcon ("src/imagenes/logo_azul.jpg");
                Icon logo1 = new ImageIcon(imagen.getImage().getScaledInstance(Mostrar_imagen.getWidth(), Mostrar_imagen.getHeight(), Image.SCALE_DEFAULT));
                Mostrar_imagen.setIcon(logo1);
                Mostrar_imagen.setVisible(true);
                this.repaint();                
                break;
            case 1:
                mensaje_imagen1 = "Imagen zona 1 de la universidad";                
                //crear objeto imagen que se establecerá en un label
                ImageIcon imagen11 = new ImageIcon ("src/imagenes/logo_blanco.jpg");
                Icon logo11 = new ImageIcon(imagen11.getImage().getScaledInstance(Mostrar_imagen.getWidth(), Mostrar_imagen.getHeight(), Image.SCALE_DEFAULT));
                Mostrar_imagen.setIcon(logo11);
                this.repaint();
                break;

            case 2:
                mensaje_imagen1 = "Imagen zona 2 de la universidad";
                break;
            case 3:
                mensaje_imagen1 = "Imagen zona 3 de la universidad";
                break; 
            case 4:
                mensaje_imagen1 = "Imagen zona 4 de la universidad";
                break;
        
        }
        switch(Asignatura_NC.getSelectedIndex()){
            case 0:
                //mensaje Asignatura se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_asignatura = "Universidad Nacional Sede Bogotá";
                break;
            case 1:
                mensaje_asignatura = "Matemáticas Básica";
                id_asignatura = 1;
                break;
            case 2:
                mensaje_asignatura = "Ingeniería Económica";
                id_asignatura = 2;
                break;
            case 3:
                mensaje_asignatura = "Ingeniería de Software I";
                id_asignatura = 3;
                break; 
            case 4:
                mensaje_asignatura = "Ingeniería de Software II";
                id_asignatura = 4;
                break;
        
        }
        Mostrar_imagen.setText("" + mensaje_imagen1);
        //centrar label
        Mostrar_imagen.setHorizontalAlignment(0);        
        Mostrar_asignatura.setText("" + mensaje_asignatura + id_asignatura);
        
      
    }//GEN-LAST:event_Buscar_imagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Asignatura_NC;
    private javax.swing.JButton Buscar_imagen;
    private javax.swing.JComboBox<String> Facultades_NC;
    private javax.swing.JLabel Mostrar_asignatura;
    private javax.swing.JLabel Mostrar_imagen;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
