/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thenarrowcompasscompany.narrow.compassv2;
//aplicar herencia desde otro archivpo
// setOpaque fueza aplicar un badground si está en true
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author dinan
 */
public class inicio_estudiante extends javax.swing.JFrame {
    public String usuarioe = "Diego";
    public String contraseñae = "12345";
    
    /**
     * Creates new form inicio_estudiante
     */
    public inicio_estudiante() {
        //inicia los componentes graficos del formulario
        initComponents();
        //centrar el jFrame        
        this.setLocationRelativeTo(null);
        //arreglo de la lista - borrador no es el completo
        String [] facultad = new String[500];
        facultad[0] = "Biología";
        facultad[1] = "Medicina";
        facultad[2] = "Química";
        facultad[3] = "Filosofía";
        for (int i = 0; i < 4 ; i++){
            this.Facultades_NC.addItem(facultad[i]);
        }
        
        String [] Asignatura = new String[500];
        Asignatura[0] = "Matemáticas Básica";
        Asignatura[1] = "Ingeniería Económica";
        Asignatura[2] = "Ingeniería de Software I";
        Asignatura[3] = "Ingeniería de Software II";
        
        for (int i = 0; i < 4; i++){
            this.Asignatura_NC.addItem(Asignatura[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        Facultades_NC = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Mostrar_imagen = new javax.swing.JLabel();
        Mostrar_asignatura = new javax.swing.JLabel();
        Asignatura_NC = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Buscar_imagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        Facultades_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultad" }));
        Facultades_NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Facultades_NCActionPerformed(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        Mostrar_imagen.setText("Imagen por defecto");

        Mostrar_asignatura.setText("Asignatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mostrar_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mostrar_asignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Mostrar_imagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mostrar_asignatura)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        Asignatura_NC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignatura" }));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Buscar_imagen.setText("Buscar");
        Buscar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_imagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Facultades_NC, 0, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Asignatura_NC, 0, 83, Short.MAX_VALUE)
                            .addComponent(Buscar_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facultades_NC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Asignatura_NC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Buscar_imagen))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Facultades_NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Facultades_NCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Facultades_NCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //crea un botón de salir.
        JOptionPane.showMessageDialog(null,"Hasta luego"); 
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1KeyReleased

    private void Buscar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_imagenActionPerformed
        // TODO add your handling code here:
        //switch case que llamará la imagen
        String mensaje_imagen1 = null;
        String mensaje_asignatura = null;
        int id_asignatura = 0;
        switch(Facultades_NC.getSelectedIndex()){
            case 0:
                //mensaje imagen se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_imagen1 = "Universidad Nacional Sede Bogotá";
                break;
            case 1:
                mensaje_imagen1 = "Imagen zona 1 de la universidad";
                break;
            case 2:
                mensaje_imagen1 = "Imagen zona 2 de la universidad";
                break;
            case 3:
                mensaje_imagen1 = "Imagen zona 3 de la universidad";
                break; 
            case 4:
                mensaje_imagen1 = "Imagen zona 4 de la universidad";
                break;
        
        }
        switch(Asignatura_NC.getSelectedIndex()){
            case 0:
                //mensaje Asignatura se refiere a una variable que definirá que se imprimirá en cada caso
                mensaje_asignatura = "Universidad Nacional Sede Bogotá";
                break;
            case 1:
                mensaje_asignatura = "Matemáticas Básica";
                id_asignatura = 1;
                break;
            case 2:
                mensaje_asignatura = "Ingeniería Económica";
                id_asignatura = 2;
                break;
            case 3:
                mensaje_asignatura = "Ingeniería de Software I";
                id_asignatura = 3;
                break; 
            case 4:
                mensaje_asignatura = "Ingeniería de Software II";
                id_asignatura = 4;
                break;
        
        }
        Mostrar_imagen.setText("" + mensaje_imagen1);
        //centrar label
        Mostrar_imagen.setHorizontalAlignment(0);        
        Mostrar_asignatura.setText("" + mensaje_asignatura + id_asignatura);
        //Mostrar_asignatura.setHorizontalAlignment(1);
        //prueba actualizar imagen
        //mensaje_imagen2.imageUpdate("com.thenarrowcompasscompany.narrow.compassv2.imagenes/logo_azul", NORMAL, WIDTH, WIDTH, WIDTH, WIDTH);
        
    }//GEN-LAST:event_Buscar_imagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Asignatura_NC;
    private javax.swing.JButton Buscar_imagen;
    private javax.swing.JComboBox<String> Facultades_NC;
    private javax.swing.JLabel Mostrar_asignatura;
    private javax.swing.JLabel Mostrar_imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
