/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thenarrowcompasscompany.narrow.compassv2;
//imprimir en otra pantalla
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dinan
 */
/*public class LoguinN extends inicio_estudiante{
   
        
}*/
public class LoguinN extends GUINC implements ILoguin_BD{
    //fondo blanco
    //fondo_loguin fondo_NCB = new fondo_loguin();
    /**
     * Creates new form LoguinN
     */
    //constructor
    
    @Override
    public void Salir(java.awt.event.ActionEvent evt){
        
        JOptionPane.showMessageDialog(null,Mostrar_mensaje());         
        System.exit(WIDTH);     
    }
    @Override
    public String Mostrar_mensaje(){
        return "Hasta Luego Loguin";
    }
    
    
    public LoguinN() {
        /*this.setContentPane(fondo_NCB);*/
        this.Mostrar_mensaje();
        initComponents();
        //centrar el Jframe
        this.setLocationRelativeTo(null);
        //Bloquea el tamaño de la ventana//
        this.setResizable(false);   
        
        String [] usuario1 = new String[500];
        usuario1[0] = "SuperAdmin";
        usuario1[1] = "Administrador";
        usuario1[2] = "Docente";
        usuario1[3] = "Estudiante";
        for (int i = 0; i < 4 ; i++){
            this.Usuario.addItem(usuario1[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LoguinNC"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        /*campo de usuario*/
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 119, -1));

        /*campo de contraseña*/
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 119, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        /*Botón de salir*/
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 69, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 36, 180, 120));

        jLabel3.setText("Iniciar Sesión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo_Usuario" }));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 183, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    
    
    
     
    /*Botón de ingresar*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario = jTextField1.getText();
        String contraseña = jPasswordField1.getText();
        String ErrorLoguin;
        ErrorLoguin = "Su usuario, tipo de usuario, o contraseña es incorrecto";
        /*valida si los campos están vacíos*/
        if(usuario.isEmpty() || contraseña.isEmpty()){
            /*imprime sin la pantalla*/
            System.out.println("Campo vacío");
            /*imprime en pantalla externa*/
            JOptionPane.showMessageDialog(null,"Algún campo está vacío");
        }
        else{
            switch(Usuario.getSelectedIndex()){
                case 0:
                    JOptionPane.showMessageDialog(null,"Seleccione un tipo de Usuario");
                    break;
                case 1:
                    //valida el usuario1 y contraseña que es 1234
                    if(usuario.equals("SuperAdmin") && contraseña.equals("Admin")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudiante pantallaIE = new inicio_estudiante();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_superadmin
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 2:
                    if(usuario.equals("Admin") && contraseña.equals("Admin")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudiante pantallaIE = new inicio_estudiante();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_admin
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 3:
                    if(usuario.equals("Docente") && contraseña.equals("1234")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudiante pantallaIE = new inicio_estudiante();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_Docente
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
                case 4:
                    if(usuario.equals("Estudiante") && contraseña.equals("12345")){
                        JOptionPane.showMessageDialog(null,"Bienvenido");
                        /*envíar al siguiente frame*/
                        inicio_estudiante pantallaIE = new inicio_estudiante();
                        //si es correcto la pantalla será visible
                        pantallaIE.setVisible(true);
                        //cambiar de frame loguin a inicio_estudiante
                        this.dispose();

                    }
                    else{
                         JOptionPane.showMessageDialog(null,ErrorLoguin);
                    }
                    break;
            }
        
       
       
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //crea un botón de salir.     
        this.Salir(evt);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoguinN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoguinN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoguinN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoguinN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoguinN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Verificar_Usuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void Modificar_Contraseña() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void Registro_Usuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void conectar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void desconectar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //imprime en pantalla la imagen de fondo
    /*class fondo_loguin extends JPanel{
        
        private Image imagenl;     
        @Override
        public void paint(Graphics NC_blanco){
            imagenl = new ImageIcon(getClass().getResource("/imagenes/logo_blanco.jpeg")).getImage();
            NC_blanco.drawImage(imagenl,getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(NC_blanco);
            
        }
        
        
    } */


}
